version: "3"
services:
  app:
    build: .
    depends_on:
      - dev_database
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: sh -c "./scripts/wait && ./scripts/docker-entrypoint.sh"
    volumes:
      - .:/usr/src/app

  dev_database:
    image: postgres:11.6-alpine
    ports:
      - "35432:5432"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/

  test_database:
    image: postgres:11.6-alpine
    ports:
      - "45432:5432"
    env_file:
      - .env.test

volumes:
  database-data:
